### ISSUE TITLE
Discrepancy with official IEC 60050 series layout

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-document#22] opened 2021-11-29 02:04 UTC
Official layout:
https://webstore.iec.ch/preview/info_iec60050-171%7Bed1.0%7Db.pdf

![](https://user-images.githubusercontent.com/11865/79018626-db2a6e00-7ba6-11ea-9826-2e6e9edf96b3.png)

Discrepancy with official IEV TOC:

From our PDF (https://github.com/glossarist/iev-document):
<img width="886" alt="Screenshot 2021-11-29 at 9 58 05 AM" src="https://user-images.githubusercontent.com/11865/143797294-d56d56e5-136d-4bd0-aa3e-82dc3b87f49f.png">

* [x] "Introduction..." line in TOC is run-in, should display second line as normal text
* [x] "Section" label missing for "Terms and definitions" sections in TOC
* [ ] Page numbering prior to first content page should be in roman numerals
* [x] Missing index

Ping @opoudjis @intelligent2013

**Comment by Intelligent2013** [comment] 2021-11-29 16:34
> "Introduction..." line in TOC is run-in, should display second line as normal text

Done:
![image](https://user-images.githubusercontent.com/5559926/143904990-e2ef0ab6-65d9-41d9-942f-7613733c7186.png)

> Page numbering prior to first content page should be in roman numerals

IEC xslt was developed in concordance with https://github.com/metanorma/mn-native-pdf/issues/111 and https://github.com/metanorma/mn-native-pdf/issues/112, where page numbers for preface sections are arabic.
But, for IEV documents (with `title-main` equals to `International Electrotechnical Vocabulary`) page numbering changed to roman and PDF renders now so:
![image](https://user-images.githubusercontent.com/5559926/143906091-33e00361-669c-40c0-afd4-59e2f00b8de3.png)

> Missing index

Index processing added into IEC xslt. Example (a few indexes were added for testing):
![image](https://user-images.githubusercontent.com/5559926/143906265-23697962-7ea8-4402-a940-cad246aae171.png)
![image](https://user-images.githubusercontent.com/5559926/143906313-8121dbb3-7814-4c87-a620-44df87271b19.png)

**Comment by Intelligent2013** [comment] 2021-11-29 16:43
> "Section" label missing for "Terms and definitions" sections in TOC

```xml
<clause id="_terms_and_definitions" obligation="normative" displayorder="5">
	<title depth="1">3<tab/>Terms and definitions</title>
	<terms id="_general_2" obligation="normative">
		<title>192-01 General</title>
		<term id="term-itemitem">
			<name>192-01-01</name>
 . . .
	<terms id="_states_and_times" obligation="normative">
		<title>192-02 States and times</title>
```

IEC xslt displays ToC titles from `terms/title`, with indentation for 2nd level:
![image](https://user-images.githubusercontent.com/5559926/143907519-37747054-22b6-4352-868e-c1aea0137bb9.png)

If I should add `Section` programmatically via xslt, please inform me the indication(condition) for it.

**Comment by ronaldtse** [comment] 2021-11-30 02:35
> IEC xslt was developed in concordance with [metanorma/mn-native-pdf#111](https://github.com/metanorma/mn-native-pdf/issues/111) and [metanorma/mn-native-pdf#112](https://github.com/metanorma/mn-native-pdf/issues/112), where page numbers for preface sections are arabic.

I didn't realise this, sorry. Let me clarify with IEC.

> If I should add `Section` programmatically via xslt, please inform me the indication(condition) for it.

This probably should be done in MN Presentation XML, so it shouldn't be an XSLT issue.

**Comment by opoudjis** [comment] 2021-12-30 06:50
Index processing already in HTML for IEC. "Introduction" also ToC'd correctly in HTML.

Page numbering would be an issue for Word, but happy not to touch it...

**Comment by opoudjis** [comment] 2021-12-30 07:01
Indexing of terms in HTML/Word is stuffing up in IEV, because terms are being introduced by a  zzSTDTitle2 paragraph rather than an h2. The structure of groupings does need to be preserved, switching it to a heading.

**Comment by opoudjis** [comment] 2021-12-30 08:56
Need improved detection of empty headings to exclude from HTML ToC.

**Comment by opoudjis** [comment] 2021-12-30 09:15
In truth, "Section 171-01" must apply to cross-references, as well as index entries. So IEV term subsections are preceded by "Section".

The problem is, that the label of the term section doesn't have Section prefixed. So:

````
<<a>>

== Terms and definitions
=== General
````

ends up as:

> Section 192-01
>
> *3. Terms and definitions*
> *192-01*. General

But the ToC is meant to be based on the title, not the cross-reference to the title. This is yet again self-indulgence from an SDO.

We will instead need to inject variant titles automatically in this context, which will be picked up for the ToC:

That will mean injecting `<variant-title type="toc">` with the Section prefixes in the Semantic XML, and an explicit `<toc>` element inserted as well.

**Comment by opoudjis** [comment] 2021-12-30 13:50
I am going to try to avoid the explicit `<toc>` element. That means leaving the `variant-title` element in place; it needs to be ignored in generation, although it still needs to reside in the Presentation XML, since it is used in both HTML, DOC and PDF to generate the index.

**Comment by opoudjis** [comment] 2021-12-31 03:39
The variant title is pointless to maintain in DOC, since DOC is dynamically updated, and will index only what is the actual title in the text. (That means that IEC manually emend their ToC to include "Section", which means they have been making a rod for their own back.)

**Comment by Intelligent2013** [comment] 2021-12-31 13:11
IEC xslt updated for variant-title rendering in ToC and bookmarks:

![image](https://user-images.githubusercontent.com/5559926/147824955-ed9d834b-942f-4e43-9d50-c6e3927c5dd9.png)

[iec-60050-192.presentation.zip](https://github.com/glossarist/iev-document/files/7796265/iec-60050-192.presentation.zip)

**Comment by Intelligent2013** [comment] 2022-01-07 11:26
Differences found between original and generated PDFs:

- [x] NORME INTERNATIONALE vs. NORME INTERNATIONAL (issue: https://github.com/metanorma/metanorma-iec/issues/130)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/148536149-8bbce996-c927-44a8-9e85-8999b3cfe6b5.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536174-78de3388-5cb2-469d-bf35-e29ee538d57d.png)


- [x] no need to render PRICE CODE of if there isn't value for it:

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536244-dadd75df-403b-4fc2-8db2-1614ad8670b6.png)


- [x] no space before Example

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/148536433-9be364b3-7ba0-457f-8df1-8b1cb736152e.png)


Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536409-123da154-f601-476b-a3bf-6c05b02bcbc8.png)


- [x] one paragraph example on one line with 'Example':

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/148536579-7ab158fb-f3fd-419a-8b8f-713e79924f29.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536621-844da7ff-3148-456b-b435-4c3a34e7d24d.png)


- [x] indent for content of example:

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/148536710-2cc0f2e0-f760-4150-af51-c3cc46a49c2a.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536754-a981072d-482a-447a-ab20-d9ec5a9123db.png)

- [x] 'EXAMPLE' should be joined with following text (see previous screenshot)


- [x] `There are no normative references in this document.`, but there are references.

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148536970-6a66d707-e52d-4d04-ad10-8f6786979876.png)
Metanorma xml:
```xml
<references id="_normative_references" normative="true" obligation="informative" displayorder="4">
			<title depth="1">2<tab/>Normative references</title>
			<p id="_">There are no normative references in this document.</p>
			<bibitem id="ISO5127" type="standard">
```

- [x] Repeated term name (for instance, 192-01-01) for second preferred item:

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/148537201-be2d08af-ce53-4bb0-a29a-3661cd6496f8.png)


Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/148537248-a3d98071-f614-41cc-b71a-3c1f73e552cf.png)

**Comment by Intelligent2013** [comment] 2022-01-07 17:50
Issues fixed:
- no need to render PRICE CODE of if there isn't value for it
- no space before Example
- one paragraph example on one line with 'Example
- indent for content of example
- 'EXAMPLE' should be joined with following text
- Repeated term name (for instance, 192-01-01) for second preferred item

**Comment by ronaldtse** [comment] 2022-01-08 02:37
Thank you @Intelligent2013 !

**Comment by opoudjis** [comment] 2022-01-17 15:41
> `There are no normative references in this document.`, but there are references.

Resolved in https://github.com/metanorma/metanorma-iec/issues/115, but codefix was undone; redoing.

**Comment by opoudjis** [comment] 2022-01-17 15:45
@Intelligent2013 Please confirm that with that, all issues are now resolved.

**Comment by Intelligent2013** [comment] 2022-01-17 17:27
> -NORME INTERNATIONALE vs. NORME INTERNATIONAL
> -There are no normative references in this document.

All known issues fixed.
But I didn't compare full text content between original and rendered pdf (in my environment metanorma xml contains english part only).

**Comment by opoudjis** [comment] 2022-01-18 12:28
Ok, I'll put this in "In review"

**Closed as completed** 2022-01-22 10:26 UTC
Labels: bug
